### ISSUE TITLE
Изменить иконку "Настройки"

### ISSUE THREAD

**Issue by MarkKaarma** [bredbrains/tthk-app#16]
Да, оно выглядит прикольно, но только при долгом изучении. По факту даже не понятно с первого раза, что это. 
И также может настройки поставить в другое место, где находятся Меню, расписание и изменение? 
Поставлю ниже шестерёнку, но цвет безусловно нужен белый. Картинка конечно не подойдет для проги (и по дизайну), но надеюсь смысл понятен.
![settings](https://user-images.githubusercontent.com/62332373/96901193-9e1b2e80-149b-11eb-9ea6-ab5c3dd6fa88.jpg)

**Comment by blinchk** [comment]
Иконку изменили, выйдет в следующей версии.
